### ISSUE TITLE
UX fixes

### ISSUE THREAD

**Issue by novohispano** [patrickmedaugh/pivot#43]

**Comment by patrickmedaugh** [comment]
Here are the UX fixes:
footer at bottom should stay on bottom of page (not creep up to the middle)
number indicator showing number of items in prospects/cart
successful investment message
"make a difference" button needs some hover styling
style business tiles and region tiles
should see all user's information on user show page
my investments info should show: region, business, amount, date
region index should show: how many projects per region
business pictures should link to their show page
should have a repayment plan
suggested amount on lend button
